import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import { Title, CheckConnectedWallet, ActionButton } from 'components/Layout'
import Head from 'next/head'
import { useWallet } from '@solana/wallet-adapter-react'
import { useEffect, useState } from 'react'
import { CANDY_MACHINE_PROGRAM_V2_ID, TOKEN_METADATA_PROGRAM_ID, MAX_METADATA_LEN, CREATOR_ARRAY_START } from 'lib/constants'
import { PublicKey } from '@solana/web3.js';
import { useConnection } from '@solana/wallet-adapter-react'
import bs58 from 'bs58';

const ViewCandyMachine: NextPage = () => {
const router = useRouter()
const account = router.query.id
const { connected } = useWallet()
const [tokens, setTokens] = useState<string[]>([])
const [imageLinks, setImageLinks] = useState<string[]>([])
const [isLoading, setIsLoading] = useState(false)
const [message, setMessage] = useState('')
const { connection } = useConnection()

  const getMintAddresses = async (firstCreatorAddress: PublicKey) => {    
    const metadataAccounts = await connection.getProgramAccounts(
      TOKEN_METADATA_PROGRAM_ID,
      {
        // The mint address is located at byte 33 and lasts for 32 bytes.
        dataSlice: { offset: 33, length: 32 },
  
        filters: [
          // Only get Metadata accounts.
          { dataSize: MAX_METADATA_LEN },
  
          // Filter using the first creator.
          {
            memcmp: {
              offset: CREATOR_ARRAY_START,
              bytes: firstCreatorAddress.toBase58(),
            },
          },
        ],
      },
    );
  
    return metadataAccounts.map((metadataAccountInfo) => (
      bs58.encode(metadataAccountInfo.account.data)
    ));
  };

  const getCandyMachineCreator = async (candyMachine: PublicKey): Promise<[PublicKey, number]> => (
    PublicKey.findProgramAddress(
      [Buffer.from('candy_machine'), candyMachine.toBuffer()],
      CANDY_MACHINE_PROGRAM_V2_ID,
    )
  );

  async function getTokens() {    
    if (!account) return
    setIsLoading(true)
    setMessage('')
    const candyMachineCreator = await getCandyMachineCreator(new PublicKey(account));       
    console.log("Previo a getMint");
    const getMint = await getMintAddresses(candyMachineCreator[0]);
    console.log("getMint", getMint);

    // let getMint = [
    //   "G5LJ55m2x9eti95LgLd34yuwFuBsUA9MvKDbLfeAEEYJ",
    //   "8j7nX3xTfXJP6eickwf6T4CBcK9RUuFDjHLEjewc6tNn",
    //   "7QJbAFsgC1XemxYukTi86zJxASeZN3ap6jNT745AQak7"
    //   ]
    if (getMint.length === 0) {
      setMessage('No tokens found')
    } else {
      // const tokenAccount = await connection.getParsedAccountInfo(new PublicKey(getMint[0]))
      // console.log("tokenAccount", tokenAccount);

      getMint.forEach(
        async (token) => {
          let fetchData = await fetch(`https://api-devnet.solscan.io/account?address=${token}`)
          let data = await fetchData.json()
          let fetchArweave = await fetch(data.data?.metadata?.data?.uri)
          let arweaveData = await fetchArweave.json()
          let imageLink = arweaveData.image
          setImageLinks([...imageLinks, imageLink])
          return imageLink
        }
      )   
      setTokens(getMint)
    }    
      
    setIsLoading(false)
  }

  useEffect(() => {
    getTokens()
  }, [])
  useEffect(() => {
    console.log(imageLinks);
    
  }, [imageLinks])

  return (
    <>
      <Head>
        <title>Verify Candy Machine</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {connected ? (
        <div className='flex justify-center items-center flex-col'>
          <Title text='Verify Candy Machine' />
          <span className='mt-8'>
            {account}{' '}
            <a
              className='text-blue-700'
              href={`https://solscan.io/account/${account}${
                connection.rpcEndpoint.includes('devnet')
                  ? '?cluster=devnet'
                  : ''
              }`}
              target='_blank'
              rel='noopener noreferrer'
            >
              View in Solscan
            </a>
          </span>
          {isLoading && <span className='mt-8'>Loading...</span>}
          {message.length !== 0 ? <span className='mt-8'>{message}</span> :
           (
             <>
              {tokens.length !== 0 && (
                <div className='flex flex-col items-center mt-8'>
                  <span>{tokens[0]}</span>
                  <span>{tokens[1]}</span>
                  <span>{tokens[2]}</span>
                  <hr />
                  <span>{imageLinks[0]}</span>
                  <span>{imageLinks[1]}</span>
                  <span>{imageLinks[2]}</span>
                </div>
              )}
             </>
           )}
        </div>
      ) : (
        <CheckConnectedWallet />
      )}
    </>
  )
}

export default ViewCandyMachine
