/* eslint-disable react-hooks/exhaustive-deps */
import type { NextPage } from 'next';
import Head from 'next/head';
import { useWallet } from '@solana/wallet-adapter-react';
import { PublicKey } from '@solana/web3.js';
import CandyMachineCard from 'components/FetchCM/CandyMachineCard';
import React, { useEffect, useState } from 'react';
import { useRPC } from 'hooks';

const CANDY_MACHINE_PROGRAM_V2_ID = new PublicKey(
  'cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ'
);

const ListCandyMachines: NextPage = () => {
  const { publicKey } = useWallet();

  const [accounts, setAccounts] = useState<string[]>([]);
  const { rpcEndpoint } = useRPC();

  async function fetchAccounts() {
    try {
      if (publicKey) {
        const accounts = await rpcEndpoint.getProgramAccounts(
          CANDY_MACHINE_PROGRAM_V2_ID,
          {
            commitment: 'confirmed',

            filters: [
              {
                memcmp: {
                  offset: 8,
                  bytes: publicKey.toBase58(),
                },
              },
            ],
          }
        );
        const accountsPubkeys = accounts.map((account) =>
          account.pubkey.toBase58()
        );
        setAccounts(accountsPubkeys);
      }
    } catch (err) {
      console.error(err);
    }
  }

  useEffect(() => {
    fetchAccounts();
  }, [publicKey]);

  return (
    <>
      <Head>
        <title>List Candy Machine</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      List Candy Machine
      <div className='grid lg:grid-cols-2 gap-y-7 mt-6 grid-flow-row grid-cols-1'>
        {accounts.length > 0 ? (
          accounts.map((account) => (
            <CandyMachineCard key={account} account={account} />
          ))
        ) : (
          <div>No Candy Machines</div>
        )}
      </div>
    </>
  );
};

export default ListCandyMachines;
