import { AnchorProvider, BN, Program } from '@project-serum/anchor'
import { useAnchorWallet, useConnection } from '@solana/wallet-adapter-react'
import { Connection, PublicKey } from '@solana/web3.js'
import { Spinner, Title, UpdateCreateCandyMachineForm, Carousel } from 'components'
import { CANDY_MACHINE_PROGRAM_V2_ID } from 'lib/candy-machine/constants'
import { IFetchedCandyMachineConfig } from 'lib/candy-machine/interfaces'
import { Account } from 'lib/candy-machine/types'
import { Nft } from 'lib/nft/interfaces'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'

const CandyMachine: NextPage = () => {
    const router = useRouter()
    const candyMachineAccount = router.query.id

    const anchorWallet = useAnchorWallet()
    const { connection } = useConnection()
    const [candyMachineConfig, setCandyMachineConfig] = useState<IFetchedCandyMachineConfig>()
    const [error, setError] = useState('')
    const [nfts, setNfts] = useState<Nft[]>([])
    const [isLoading, setIsLoading] = useState(false)

    async function viewNfts(e: React.ChangeEvent<HTMLInputElement>) {
        if (!e.target.files || e.target.files.length == 0) {
            window.alert('No files uploaded')
            return
        }
        let cacheData = await e.target.files[0].text()
        let cacheDataJson = JSON.parse(cacheData)
        if (cacheDataJson?.program?.candyMachine === candyMachineAccount) {
            const nfts = Object.values(cacheDataJson.items).map((nft: any) => {
                return {
                    image: nft.imageLink,
                    name: nft.name,
                }
            })

            setNfts(nfts)
        } else {
            alert('This cache file is not from this candy machine')
        }
    }

    async function fetchCandyMachine({
        candyMachineAccount,
        connection,
    }: {
        candyMachineAccount: Account
        connection: Connection
    }): Promise<IFetchedCandyMachineConfig | undefined> {
        if (candyMachineAccount && anchorWallet) {
            try {
                setIsLoading(true)
                const provider = new AnchorProvider(connection, anchorWallet, {
                    preflightCommitment: 'processed',
                })

                const idl = await Program.fetchIdl(CANDY_MACHINE_PROGRAM_V2_ID, provider)

                const program = new Program(idl!, CANDY_MACHINE_PROGRAM_V2_ID, provider)

                const state: any = await program.account.candyMachine.fetch(new PublicKey(candyMachineAccount))

                state.data.solTreasuryAccount = state.wallet
                state.data.itemsRedeemed = state.itemsRedeemed
                console.log('candyMachineConfig: ', state)
                setIsLoading(false)

                return state.data
            } catch (err) {
                console.error(err)
                setIsLoading(false)
                setError((err as Error).message)
            }
        }
    }

    useEffect(() => {
        fetchCandyMachine({ candyMachineAccount, connection }).then(setCandyMachineConfig)
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [candyMachineAccount, connection, anchorWallet])

    return (
        <>
            <Head>
                <title>Update Candy Machine</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div className='container flex justify-center items-center flex-col'>
                <Title text='Update Candy Machine' />
                <div className='mt-8 flex flex-col text-center'>
                    <span className='break-all border border-slate-300 shadow-xl py-2 px-4 rounded-lg text-center'>
                        {candyMachineAccount}{' '}
                    </span>
                    <a
                        className='text-[hsl(258,52%,56%)] mt-4'
                        href={`https://solscan.io/account/${candyMachineAccount}?cluster=devnet`}
                        target='_blank'
                        rel='noopener noreferrer'
                    >
                        View in Solscan
                    </a>
                </div>
                {isLoading && <Spinner />}
                {error && (
                    <div className='flex flex-col items-center justify-center mt-11'>
                        Error fetching candy machine config
                        <button
                            className='rounded-lg bg-slate-400 p-2 mt-4'
                            onClick={() => fetchCandyMachine({ candyMachineAccount, connection })}
                        >
                            Fetch again
                        </button>
                    </div>
                )}

                {!error && candyMachineConfig?.uuid && (
                    <div className='mt-5 flex flex-col text-center'>
                        <span className='mt-5'>
                            There are{' '}
                            {new BN(candyMachineConfig.itemsAvailable).toNumber() -
                                new BN(candyMachineConfig.itemsRedeemed).toNumber()}{' '}
                            unminted NFT.
                        </span>
                        <span className='mt-2'>
                            {new BN(candyMachineConfig.itemsRedeemed).toNumber()} redeemed NFT.
                        </span>
                        {new BN(candyMachineConfig.itemsAvailable).toNumber() -
                            new BN(candyMachineConfig.itemsRedeemed).toNumber() !==
                            0 && (
                            <>
                                <label
                                    htmlFor='cache'
                                    className='m-8 px-4 py-2 rounded-xl bg-slate-200 hover:bg-slate-100 transition-all duration-300 ease-linear font-medium border border-gray-500 inline-block cursor-pointer'
                                >
                                    Upload Cache file to view NFTs
                                </label>
                                <input
                                    type='file'
                                    id='cache'
                                    name='cache'
                                    className='w-full px-2 hidden'
                                    onChange={viewNfts}
                                />
                            </>
                        )}
                        {nfts.length !== 0 && (
                            <Carousel
                                carouselData={nfts.map((nft) => ({
                                    title: nft.name,
                                    image: nft.image,
                                }))}
                            />
                        )}
                        <UpdateCreateCandyMachineForm
                            fetchedValues={candyMachineConfig}
                            updateCandyMachine
                            candyMachinePubkey={candyMachineAccount}
                        />
                    </div>
                )}
            </div>
        </>
    )
}

export default CandyMachine
