import type { NextPage } from 'next';
import Head from 'next/head';
import Form from 'components/CreateCM/Form';
import { Title } from 'components/Layout';
const CreateCandyMachine: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Candy Machine</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex justify-center items-center flex-col'>
        <Title text='Create Candy Machine' />
      </div>
      <Form />
    </>
  );
};

export default CreateCandyMachine;
