import { useWallet } from '@solana/wallet-adapter-react'
import { CheckConnectedWallet, Title, UpdateCreateCandyMachineForm } from 'components'
import type { NextPage } from 'next'
import Head from 'next/head'

const CreateCandyMachine: NextPage = () => {
    const { publicKey } = useWallet()

    if (!publicKey) {
        return <CheckConnectedWallet />
    }

    return (
        <>
            <Head>
                <title>Create Candy Machine</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div className='container flex justify-center items-center flex-col'>
                <Title text='Create Candy Machine' />
                <UpdateCreateCandyMachineForm />
            </div>
        </>
    )
}

export default CreateCandyMachine
