import type { NextPage } from "next";
import Head from "next/head";

const ListCandyMachines: NextPage = () => {
  return (
    <>
      <Head>
        <title>List Candy Machine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      List Candy Machine
    </>
  );
};

export default ListCandyMachines;
