name: Release
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Preparing release body
        run: |
          touch CHANGELOG.md
          echo '### Changelog' >> CHANGELOG.md
          echo '------' >> CHANGELOG.md
          cat CHANGELOG.md
      - name: Create Release
        uses: actions/create-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Sugar Rush ${{ github.ref }}
          body_path: CHANGELOG.md
